import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { ExternalLink, Code, Search, X, Activity } from 'lucide-react';
// eslint-disable-next-line no-unused-vars
import { motion, AnimatePresence } from 'framer-motion';

export default function Websites() {
    const [leads, setLeads] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState('');
    const [statusFilter, setStatusFilter] = useState('all');
    const [previewHtml, setPreviewHtml] = useState(null);

    useEffect(() => {
        fetchWebsites();
    }, []);

    async function fetchWebsites() {
        try {
            // Fetch leads that have at least a generated website
            const { data, error } = await supabase
                .from('leads')
                .select('*')
                .in('status', ['created', 'published', 'pitched', 'completed'])
                .order('updated_at', { ascending: false });

            if (error) throw error;
            setLeads(data || []);
        } catch (error) {
            console.error('Error fetching websites:', error);
        } finally {
            setLoading(false);
        }
    }

    const filteredLeads = leads.filter(lead => {
        const matchesSearch = lead.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
            lead.place_id?.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesStatus = statusFilter === 'all' || lead.status === statusFilter;
        return matchesSearch && matchesStatus;
    });

    const statuses = ['all', 'created', 'published', 'pitched', 'completed'];

    return (
        <div className="space-y-6 pb-20">
            <header className="flex flex-col md:flex-row md:items-end justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-zinc-100">Live Sites & Previews</h1>
                    <p className="text-zinc-400 mt-1">Direct access to the HTML generated by the Creator agent.</p>
                </div>
                <div className="flex flex-col sm:flex-row gap-3">
                    <div className="flex gap-2">
                        {statuses.map(s => (
                            <button
                                key={s}
                                onClick={() => setStatusFilter(s)}
                                className={`px-3 py-1.5 rounded-lg text-xs font-medium capitalize transition-colors \${
                                    statusFilter === s 
                                    ? 'bg-primary text-white' 
                                    : 'bg-zinc-800 text-zinc-400 hover:bg-zinc-700 hover:text-zinc-200'
                                }`}
                            >
                                {s}
                            </button>
                        ))}
                    </div>
                    <div className="relative">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500" />
                        <input
                            type="text"
                            placeholder="Search leads..."
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="pl-9 pr-4 py-2 bg-zinc-900 border border-zinc-700 rounded-lg text-sm text-zinc-100 w-full sm:w-64 focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/50"
                        />
                    </div>
                </div>
            </header>

            {loading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                    {[...Array(8)].map((_, i) => (
                        <div key={i} className="bg-surface border border-zinc-800 rounded-2xl h-64 animate-pulse"></div>
                    ))}
                </div>
            ) : filteredLeads.length === 0 ? (
                <div className="bg-surface border border-zinc-800 rounded-2xl p-12 text-center">
                    <Code className="h-12 w-12 text-zinc-700 mx-auto mb-4" />
                    <h3 className="text-lg font-medium text-zinc-300">No sites found</h3>
                    <p className="text-zinc-500 mt-1">Trigger the pipeline to generate new websites.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                    {filteredLeads.map((lead, i) => (
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.05 }}
                            key={lead.place_id}
                            className="bg-surface border border-zinc-800 rounded-2xl overflow-hidden hover:border-zinc-700 transition-colors group flex flex-col"
                        >
                            {/* Browser Header Mock */}
                            <div className="bg-zinc-900 px-4 py-3 border-b border-zinc-800 flex items-center gap-2">
                                <div className="flex gap-1.5 opacity-50">
                                    <div className="w-2.5 h-2.5 rounded-full bg-red-400"></div>
                                    <div className="w-2.5 h-2.5 rounded-full bg-amber-400"></div>
                                    <div className="w-2.5 h-2.5 rounded-full bg-green-400"></div>
                                </div>
                                <div className="flex-1 text-center truncate text-[10px] text-zinc-500 font-mono pr-8">
                                    {lead.vercel_url ? lead.vercel_url.replace('https://', '') : 'preview.local'}
                                </div>
                            </div>

                            <div className="p-5 flex-1 flex flex-col items-center justify-center text-center relative overflow-hidden bg-zinc-900/30">
                                {/* Subtle decorative bg */}
                                <div className="absolute inset-0 opacity-10 blur-xl">
                                    <div className="absolute top-0 right-0 w-32 h-32 bg-primary rounded-full mix-blend-screen"></div>
                                    <div className="absolute bottom-0 left-0 w-32 h-32 bg-purple-500 rounded-full mix-blend-screen"></div>
                                </div>

                                <div className="relative z-10 w-full">
                                    <h3 className="font-semibold text-zinc-100 text-lg mb-1 truncate px-2" title={lead.name}>
                                        {lead.name}
                                    </h3>
                                    <span className={`inline-block px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider mb-4
                                        ${lead.status === 'completed' ? 'bg-indigo-500/10 text-indigo-400' :
                                            lead.status === 'published' || lead.status === 'pitched'
                                                ? 'bg-emerald-500/10 text-emerald-400'
                                                : 'bg-purple-500/10 text-purple-400'}`}>
                                        {lead.status}
                                    </span>

                                    {lead.login_count > 0 && (
                                        <div className="mt-2 text-[10px] text-emerald-400 font-medium flex items-center justify-center gap-1 bg-emerald-400/10 px-2 py-0.5 rounded-full inline-flex">
                                            <Activity className="h-3 w-3" />
                                            {lead.login_count} Logins • Last: {new Date(lead.last_login_at).toLocaleDateString()}
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div className="p-4 border-t border-zinc-800 bg-zinc-900/50 flex gap-2">
                                <button
                                    onClick={() => setPreviewHtml(lead.website_html)}
                                    disabled={!lead.website_html}
                                    className="flex-1 py-2 px-3 bg-zinc-800 hover:bg-zinc-700 disabled:opacity-50 text-white text-xs font-medium rounded-lg transition-colors flex items-center justify-center gap-1.5"
                                >
                                    <Code className="h-3.5 w-3.5" /> Raw Code
                                </button>

                                <a
                                    href={lead.vercel_url || '#'}
                                    target={lead.vercel_url ? "_blank" : "_self"}
                                    rel="noreferrer"
                                    onClick={(e) => !lead.vercel_url && e.preventDefault()}
                                    className={`flex-1 py-2 px-3 text-white text-xs font-medium rounded-lg transition-colors flex items-center justify-center gap-1.5
                                        ${lead.vercel_url
                                            ? 'bg-primary hover:bg-blue-600 shadow-lg shadow-primary/20'
                                            : 'bg-zinc-800/50 text-zinc-500 cursor-not-allowed'}`}
                                >
                                    <ExternalLink className="h-3.5 w-3.5" /> Vercel
                                </a>
                            </div>
                        </motion.div>
                    ))}
                </div>
            )}

            {/* Full Screen HTML Preview Modal */}
            <AnimatePresence>
                {previewHtml && (
                    <M.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
                    >
                        <motion.div
                            initial={{ scale: 0.95, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            exit={{ scale: 0.95, opacity: 0 }}
                            className="bg-black border border-zinc-800 rounded-xl w-full max-w-6xl h-[90vh] flex flex-col overflow-hidden shadow-2xl"
                        >
                            <div className="p-3 bg-zinc-900 border-b border-zinc-800 flex justify-between items-center px-4 shrink-0">
                                <div className="flex items-center gap-2 text-zinc-400 font-mono text-sm">
                                    <Code className="h-4 w-4 text-primary" />
                                    <span>Raw HTML Preview (Sandboxed)</span>
                                </div>
                                <button
                                    onClick={() => setPreviewHtml(null)}
                                    className="p-1 hover:bg-zinc-800 hover:text-white rounded text-zinc-400 transition-colors"
                                >
                                    <X className="h-5 w-5" />
                                </button>
                            </div>
                            <div className="flex-1 bg-white relative">
                                <iframe
                                    srcDoc={previewHtml}
                                    title="Website Preview"
                                    className="w-full h-full border-none"
                                    sandbox="allow-scripts allow-same-origin"
                                />
                            </div>
                        </motion.div>
                    </M.div>
                )}
            </AnimatePresence>
        </div>
    );
}
