require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

async function updateQueries() {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const newQueries = [
        "restaurant in Olaya Riyadh",
        "cafe in Tahlia Street Riyadh",
        "gym in Malaz Riyadh",
        "dental clinic in Riyadh",
        "barbershop in Hittin Riyadh",
        "flower shop in Riyadh",
        "boutique in Riyadh",
        "bakery in Riyadh",
        "electronics repair in Riyadh",
        "car wash Riyadh",
        "coffee roastery Riyadh",
        "furniture store Riyadh",
        "spa in Al Mohammadiyyah Riyadh",
        "optician in Riyadh",
        "bookstore in Riyadh",
        "dermatology clinic Riyadh",
        "pediatrician Riyadh",
        "physiotherapy center Riyadh",
        "veterinary clinic Riyadh",
        "yoga studio Riyadh",
        "pilates studio Riyadh",
        "law firm Riyadh",
        "accounting office Riyadh",
        "digital marketing agency Riyadh",
        "interior design Riyadh",
        "architectural firm Riyadh",
        "landscaping service Riyadh",
        "luxury watches Riyadh",
        "custom tailor Riyadh",
        "jewelry store Riyadh",
        "eyewear boutique Riyadh",
        "japanese restaurant Riyadh",
        "specialty burger Riyadh",
        "fine dining Riyadh",
        "event catering Riyadh",
        "car detailing Riyadh",
        "luxury car rental Riyadh",
        "pharmacy Riyadh",
        "nutritionist Riyadh",
        "beauty salon Riyadh",
        "day spa Riyadh",
        "perfume shop Riyadh",
        "gift shop Riyadh",
        "toy store Riyadh",
        "stationary shop Riyadh",
        "printing service Riyadh",
        "it consulting Riyadh",
        "cybersecurity firm Riyadh",
        "real estate agency Riyadh",
        "travel agency Riyadh",
        "laundry service Riyadh",
        "tailoring shop Riyadh",
        "bridal boutique Riyadh",
        "nursery school Riyadh",
        "language learning center Riyadh",
        "music school Riyadh",
        "art gallery Riyadh",
        "fitness center Riyadh",
        "crossfit gym Riyadh",
        "healthy food restaurant Riyadh",
        "ice cream shop Riyadh",
        "pet supplies Riyadh",
        "hardware store Riyadh",
        "paint shop Riyadh",
        "plumbing service Riyadh",
        "electrical contractor Riyadh",
        "ac repair service Riyadh",
        "cleaning service Riyadh",
        "pest control Riyadh",
        "security company Riyadh",
        "logistics company Riyadh",
        "courier service Riyadh",
        "moving company Riyadh",
        "storage facility Riyadh",
        "auto showroom Riyadh",
        "used car dealer Riyadh",
        "tire shop Riyadh",
        "car battery shop Riyadh",
        "glass repair Riyadh",
        "upholstery shop Riyadh",
        "cabinet maker Riyadh",
        "flooring contractor Riyadh",
        "roofing service Riyadh",
        "swimming pool builder Riyadh",
        "solar energy company Riyadh",
        "water purification Riyadh",
        "office supplies Riyadh",
        "uniform supplier Riyadh",
        "industrial equipment Riyadh",
        "construction company Riyadh",
        "engineering consultant Riyadh",
        "training center Riyadh",
        "recruitment agency Riyadh",
        "travel insurance Riyadh",
        "medical center Al Sahafa Riyadh",
        "wellness center Al Ghadir Riyadh",
        "sports club Al Nakheel Riyadh",
        "martial arts Riyadh",
        "dance studio Riyadh",
        "photography studio Riyadh",
        "video production Riyadh",
        "advertising agency Riyadh",
        "public relations Riyadh",
        "translation service Riyadh",
        "event planner Riyadh",
        "wedding planner Riyadh",
        "flower delivery Riyadh",
        "confectionery Riyadh",
        "chocolate shop Riyadh",
        "dates shop Riyadh",
        "honey shop Riyadh",
        "organic store Riyadh",
        "vape shop Riyadh",
        "smoke shop Riyadh",
        "hobby shop Riyadh",
        "pet groomer Riyadh",
        "pet hotel Riyadh",
        "animal hospital Riyadh",
        "driving school Riyadh",
        "car insurance Riyadh",
        "home insurance Riyadh",
        "life insurance Riyadh",
        "tax consultant Riyadh",
        "business consultant Riyadh"
    ];

    const { data, error } = await supabase
        .from('settings')
        .update({ value: newQueries })
        .eq('key', 'search_queries')
        .select();

    if (error) {
        console.error('Error updating queries:', error);
        return;
    }

    console.log('--- Search Queries updated successfully ---');
    console.log(JSON.stringify(data[0].value, null, 2));
}

updateQueries();
