const { GoogleGenAI } = require('@google/genai');

/**
 * Retoucher Agent
 * Acts as an aesthetic auditor and quality controller.
 * Instead of generating the full HTML back (which times out Vercel), it returns a JSON array of targeted string replacements.
 */
class RetoucherAgent {
    constructor() {
        this.apiKey = process.env.GEMINI_API_KEY;
        if (!this.apiKey) {
            throw new Error('GEMINI_API_KEY is not defined in environment variables.');
        }
        this.ai = new GoogleGenAI({ apiKey: this.apiKey });
    }

    /**
     * Refines and polishes the raw HTML using JSON replacements
     * @param {string} rawHtml - The HTML string generated by the Creator agent
     * @param {Object} business - The business details
     * @returns {Promise<string>} Polished HTML string
     */
    async retouchWebsite(rawHtml, business) {
        console.log(`[Retoucher] Auditing website for: ${business.name} (Using JSON targeted edits)...`);

        const promptConfig = {
            system: `You are a world-class UI/UX Designer and strict Aesthetic Auditor.
Your job is to take raw, functional HTML/Tailwind code and find duplicate/bad assets and improve the Tailwind CSS classes.
CRITICAL: You MUST ONLY output a raw JSON array of targeted string replacements. DO NOT output HTML.`,

            instructions: `Review the provided HTML code and find ways to apply these aesthetic rules:

1. **No Duplicate Media (CRITICAL)**: The Creator often uses the exact same image URL multiple times. Scan the HTML for duplicate \`<img src="...">\` OR \`url(...)\` usages. Create a replacement for duplicate occurrences using \`https://loremflickr.com/1200/800/{industry_keyword}?random={number}\`.
2. **Premium Tailwind Aesthetics**: Find generic Tailwind classes like \`bg-white\` or \`shadow-md\` and replace them with premium classes like \`backdrop-blur-md bg-white/60 shadow-xl shadow-indigo-500/10 transition-all hover:scale-105\`.

CRITICAL INSTRUCTION: Your output MUST be strictly a valid JSON array of objects. Each object must have an \"old\" key (the exact exact literal string in the HTML to replace) and a \"new\" key (the new literal string).
DO NOT use regex in the \"old\" string. It must literally match the HTML text perfectly.

Example Output format:
[
  {
    "old": "<img src=\\"http://example.com/photo.jpg\\" alt=\\"generic\\">",
    "new": "<img src=\\"https://loremflickr.com/1200/800/clinic?random=1\\" alt=\\"generic\\">"
  },
  {
    "old": "class=\\"bg-white p-6 shadow-md rounded-lg\\"",
    "new": "class=\\"bg-white/80 backdrop-blur-md p-6 shadow-xl rounded-2xl transition hover:scale-105\\""
  }
]`
        };

        const prompt = `
      ${promptConfig.system}
      
      Business Name: ${business.name}
      Industry: ${(business.types || []).join(', ')}
      
      Requirements:
      ${promptConfig.instructions}
      
      Raw HTML to Audit:
      \`\`\`html
      ${rawHtml}
      \`\`\`
    `;

        try {
            // Keep a strict time limit to prevent Vercel timeouts. We give JSON Retoucher ~45s.
            let timeoutId;
            const timeoutPromise = new Promise((_, reject) => {
                timeoutId = setTimeout(() => reject(new Error('Gemini API request timed out after 45 seconds')), 45000);
            });

            const response = await Promise.race([
                this.ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: prompt,
                }),
                timeoutPromise
            ]);

            clearTimeout(timeoutId);

            let jsonOutput = response.text || '';
            if (!jsonOutput) {
                return rawHtml; // Fallback gracefully if AI is empty
            }

            // Extract JSON from markdown blocks if present
            const jsonMatch = jsonOutput.match(/\[[\s\S]*\]/);
            if (!jsonMatch) {
                console.warn("[Retoucher] Failed to parse JSON. Skipping retouch step.", jsonOutput.substring(0, 100));
                return rawHtml;
            }

            let edits = [];
            try {
                edits = JSON.parse(jsonMatch[0]);
            } catch (e) {
                console.error("[Retoucher] Invalid JSON returned:", e.message);
                return rawHtml;
            }

            console.log(`[Retoucher] Applying ${edits.length} aesthetic edits to the HTML...`);

            let finalHtml = rawHtml;
            for (const edit of edits) {
                if (edit.old && edit.new) {
                    // Fast string replace. We only replace the first occurrence per edit rule 
                    // to avoid blindly overwriting everything if the prompt was greedy.
                    finalHtml = finalHtml.replace(edit.old, edit.new);
                }
            }

            console.log(`[Retoucher] Audits successfully applied for ${business.name}.`);
            return finalHtml;
        } catch (error) {
            console.error(`[Retoucher] Error auditing website: ${error.message}. Returning raw HTML fallback.`);
            // Fallback to RAW html so the pipeline never stalls
            return rawHtml;
        }
    }
}

module.exports = RetoucherAgent;
